version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Pastikan .env ada di .gitignore
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Ambil dari .env atau environment variable
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Ambil dari .env atau environment variable
      POSTGRES_DB: ${POSTGRES_DB}  # Ambil dari .env atau environment variable
    ports:
      - "5432:5432"
